
export const SEARCH = 'SEARCH';

export const FETCH_ITUNESDATA_PENDING="FETCH_ITUNESDATA_PENDING"; 
export const FETCH_ITUNESDATA="FETCH_ITUNESDATA";
export const FETCH_ITUNESDATA_ERROR="FETCH_ITUNESDATA_ERROR";
